module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFilesAfterEnv: ['<rootDir>/src/tests/setup.ts'],
  testMatch: [
    '<rootDir>/src/tests/**/*.test.ts',
    '<rootDir>/src/tests/**/*.test.tsx',
  ],
  moduleNameMapper: {
    '^@tdarts/core$': '<rootDir>/../../packages/core/src/index.ts',
    '^@tdarts/services$': '<rootDir>/../../packages/services/src/index.ts',
    '^@/database/services/(.*)$': '<rootDir>/../../packages/services/src/$1',
    '^@/database/models/(.*)$': '<rootDir>/../../packages/core/src/models/$1',
    '^@/interface/(.*)$': '<rootDir>/../../packages/core/src/interfaces/$1',
    '^@/lib/mongoose$': '<rootDir>/../../packages/core/src/lib/mongoose.ts',
    '^@/lib/mailer$': '<rootDir>/../../packages/core/src/lib/mailer.ts',
    '^@/lib/email-layout$': '<rootDir>/../../packages/core/src/lib/email-layout.ts',
    '^@/lib/email-resend$': '<rootDir>/../../packages/core/src/lib/email-resend.ts',
    '^@/lib/events$': '<rootDir>/../../packages/core/src/lib/events.ts',
    '^@/lib/date-time$': '<rootDir>/../../packages/core/src/lib/date-time.ts',
    '^@/lib/club-location-completeness$': '<rootDir>/../../packages/core/src/lib/club-location-completeness.ts',
    '^@/lib/leaguePointSystems$': '<rootDir>/../../packages/core/src/lib/leaguePointSystems.ts',
    '^@/lib/utils$': '<rootDir>/../../packages/core/src/lib/utils.ts',
    '^@/middleware/errorHandle$': '<rootDir>/src/middleware/errorHandle.ts',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  testTimeout: 15000,
};
