import {
  Activity,
  BarChart3,
  Database,
  FileText,
  Flag,
  LayoutDashboard,
  Megaphone,
  MessageSquare,
  Settings,
  Shield,
  Swords,
  Target,
  Trophy,
  Users,
  Wrench,
  type LucideIcon,
} from 'lucide-react';
import type { AdminNavIcon } from '@/features/admin/types/nav';

export const AdminNavIcons: Record<AdminNavIcon, LucideIcon> = {
  dashboard: LayoutDashboard,
  users: Users,
  clubs: Flag,
  players: Target,
  tournaments: Trophy,
  matches: Swords,
  leagues: BarChart3,
  subscriptions: FileText,
  observability: Activity,
  support: MessageSquare,
  feedback: MessageSquare,
  system: Settings,
  tools: Wrench,
  featureAccess: Shield,
  ads: Megaphone,
  content: FileText,
  data: Database,
};
