import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { withApiTelemetry } from '@/lib/api-telemetry';
import { handleError } from '@/middleware/errorHandle';
import { TournamentService } from '@/database/services/tournament.service';
import { PlayerService } from '@/database/services/player.service';
import { MatchService } from '@/database/services/match.service';
import { MatchModel } from '@/database/models/match.model';

type Params = { params: Promise<{ action: string[] }> };
const CHECKIN_BATCH_SIZE = 25;

const createTournamentSchema = z.object({
  name: z.string().min(1).optional(),
  boardsCount: z.number().int().min(1).max(32).optional(),
  maxPlayers: z.number().int().min(2).max(512).optional(),
  format: z.enum(['group_knockout', 'knockout']).optional(),
  startingScore: z.number().int().min(101).max(1001).optional(),
  entryFee: z.number().min(0).optional(),
  participationMode: z.enum(['individual', 'pair', 'team']).optional(),
  startDate: z.string().datetime().optional(),
  type: z.string().optional(),
});

const tournamentCodeSchema = z.object({
  tournamentCode: z.string().min(1),
});

const addPlayerSchema = z.object({
  tournamentCode: z.string().min(1),
  playerName: z.string().min(1).optional(),
  playerId: z.string().min(1).optional(),
});

const generateKnockoutSchema = z.object({
  tournamentCode: z.string().min(1),
  selectedPlayers: z.number().int().positive().optional(),
});

const startMatchSchema = z.object({
  tournamentCode: z.string().min(1),
  matchId: z.string().min(1),
  boardNumber: z.number().int().positive().optional(),
  legsToWin: z.number().int().positive().max(10).optional(),
  startingPlayer: z.union([z.literal(1), z.literal(2)]).optional(),
});

const finishMatchSchema = z.object({
  matchId: z.string().min(1),
  player1LegsWon: z.number().int().min(0).optional(),
  player2LegsWon: z.number().int().min(0).optional(),
});

const updateBoardStatusSchema = z.object({
  matchId: z.string().min(1),
});

const finishTournamentSchema = z.object({
  tournamentCode: z.string().min(1),
  thirdPlacePlayerId: z.string().min(1).optional(),
});

const listMatchesSchema = z.object({
  tournamentCode: z.string().min(1),
  statuses: z.array(z.enum(['pending', 'ongoing', 'finished'])).optional(),
  limit: z.number().int().min(1).max(1000).optional(),
  summaryOnly: z.boolean().optional(),
});

function assertLoadTestAccess(request: NextRequest) {
  if (process.env.LOAD_TEST_MODE !== 'true') {
    return NextResponse.json({ error: 'Load test mode is disabled' }, { status: 403 });
  }

  const configuredSecret = process.env.LOAD_TEST_SECRET;
  const providedSecret = request.headers.get('x-load-test-secret');
  if (!configuredSecret) {
    return NextResponse.json({ error: 'LOAD_TEST_SECRET is not configured on the server' }, { status: 500 });
  }
  if (!providedSecret) {
    return NextResponse.json({ error: 'Missing x-load-test-secret header' }, { status: 403 });
  }
  if (providedSecret !== configuredSecret) {
    return NextResponse.json({ error: 'Invalid x-load-test-secret header' }, { status: 403 });
  }

  if (!process.env.LOAD_TEST_USER_ID || !process.env.LOAD_TEST_CLUB_ID) {
    return NextResponse.json(
      { error: 'Missing LOAD_TEST_USER_ID or LOAD_TEST_CLUB_ID environment variables' },
      { status: 500 }
    );
  }

  return null;
}

function buildBoards(boardsCount: number) {
  return Array.from({ length: boardsCount }, (_, index) => ({
    boardNumber: index + 1,
    name: `Load Board ${index + 1}`,
    isActive: true,
    status: 'waiting' as const,
  }));
}

function buildTournamentPayload(input: z.infer<typeof createTournamentSchema>) {
  const now = new Date();
  const boardCount = input.boardsCount ?? 8;
  const parsedStartDate = input.startDate ? new Date(input.startDate) : now;

  return {
    clubId: process.env.LOAD_TEST_CLUB_ID!,
    tournamentPlayers: [],
    groups: [],
    knockout: [],
    boards: buildBoards(boardCount),
    tournamentSettings: {
      status: 'pending',
      name: input.name || `Load Test Tournament ${now.toISOString()}`,
      description: 'Generated by Artillery load test',
      startDate: parsedStartDate,
      maxPlayers: input.maxPlayers ?? 80,
      format: input.format ?? 'group_knockout',
      startingScore: input.startingScore ?? 501,
      boardCount,
      entryFee: input.entryFee ?? 0,
      tournamentPassword: 'loadtest-password',
      location: null,
      type: input.type || 'amateur',
      registrationDeadline: null,
      participationMode: input.participationMode ?? 'individual',
    },
    createdAt: now,
    updatedAt: now,
    isArchived: false,
    isCancelled: false,
    isSandbox: true,
    verified: false,
    paymentStatus: 'none',
    isActive: true,
  };
}

async function postHandler(request: NextRequest, context: Params) {
  const blockedResponse = assertLoadTestAccess(request);
  if (blockedResponse) {
    return blockedResponse;
  }

  const userId = process.env.LOAD_TEST_USER_ID!;
  const { action } = await context.params;
  const actionName = action?.[0];
  const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;
  try {
    switch (actionName) {
      case 'create-tournament': {
        const payload = createTournamentSchema.parse(body);
        const tournamentPayload = buildTournamentPayload(payload);
        const tournament = await TournamentService.createTournament(tournamentPayload as any);
        return NextResponse.json({
          success: true,
          tournamentId: tournament._id?.toString?.() || String(tournament._id),
          tournamentCode: tournament.tournamentId,
          isSandbox: Boolean((tournament as any).isSandbox),
        });
      }

      case 'add-player': {
        const payload = addPlayerSchema.parse(body);
        const playerName = payload.playerName || `Load Player ${Math.floor(Math.random() * 1_000_000_000)}`;
        const playerId = payload.playerId || (await PlayerService.findOrCreatePlayerByName(playerName))._id.toString();
        await TournamentService.addTournamentPlayer(payload.tournamentCode, playerId);
        await TournamentService.updateTournamentPlayerStatus(payload.tournamentCode, playerId, 'checked-in');
        return NextResponse.json({ success: true, playerId, status: 'checked-in' });
      }

      case 'generate-groups': {
        const payload = tournamentCodeSchema.parse(body);
        await TournamentService.generateGroups(payload.tournamentCode, userId);
        return NextResponse.json({ success: true });
      }

      case 'check-in-all-players': {
        const payload = tournamentCodeSchema.parse(body);
        const playerIds = await TournamentService.getTournamentPlayerIds(payload.tournamentCode);
        let checkedInCount = 0;
        let failedCount = 0;

        for (let i = 0; i < playerIds.length; i += CHECKIN_BATCH_SIZE) {
          const batch = playerIds.slice(i, i + CHECKIN_BATCH_SIZE);
          const results = await Promise.allSettled(
            batch.map((playerId) =>
              TournamentService.updateTournamentPlayerStatus(payload.tournamentCode, playerId, 'checked-in'),
            ),
          );
          for (const result of results) {
            if (result.status === 'fulfilled' && result.value) {
              checkedInCount += 1;
            } else {
              failedCount += 1;
            }
          }
        }

        return NextResponse.json({ success: true, checkedInCount, failedCount });
      }

      case 'generate-knockout': {
        const payload = generateKnockoutSchema.parse(body);
        await TournamentService.generateKnockout(payload.tournamentCode, userId, {
          qualifiersPerGroup: payload.selectedPlayers,
        });
        return NextResponse.json({ success: true });
      }

      case 'start-match': {
        const payload = startMatchSchema.parse(body);
        const match = await MatchService.startMatch(
          payload.tournamentCode,
          payload.matchId,
          payload.legsToWin || 3,
          payload.startingPlayer || 1,
        );
        return NextResponse.json({
          success: true,
          matchId: (match as any)?._id?.toString?.() || payload.matchId,
          status: (match as any)?.status || 'ongoing',
        });
      }

      case 'finish-match': {
        const payload = finishMatchSchema.parse(body);
        const p1 = payload.player1LegsWon ?? 3;
        const p2 = payload.player2LegsWon ?? Math.floor(Math.random() * 3);
        const match = await MatchModel.findOneAndUpdate(
          { _id: payload.matchId },
          [
            {
              $set: {
                status: 'finished',
                winnerId: {
                  $cond: [{ $gt: [p1, p2] }, '$player1.playerId', '$player2.playerId'],
                },
                'player1.legsWon': p1,
                'player2.legsWon': p2,
                updatedAt: '$$NOW',
              },
            },
          ],
          {
            new: true,
            projection: { _id: 1, status: 1, type: 1 },
          },
        ).lean();
        if (!match) {
          return NextResponse.json({ error: 'Match not found' }, { status: 404 });
        }
        if ((match as any).type === 'knockout') {
          await TournamentService.autoAdvanceKnockoutWinner(payload.matchId).catch(() => null);
        }
        return NextResponse.json({
          success: true,
          matchId: (match as any)._id?.toString?.() || payload.matchId,
          status: (match as any).status || 'finished',
        });
      }

      case 'update-board-status': {
        const payload = updateBoardStatusSchema.parse(body);
        await TournamentService.updateBoardStatusAfterMatch(payload.matchId);
        return NextResponse.json({ success: true });
      }

      case 'finish-tournament': {
        const payload = finishTournamentSchema.parse(body);
        await TournamentService.finishTournament(
          payload.tournamentCode,
          userId,
          payload.thirdPlacePlayerId,
        );
        return NextResponse.json({ success: true });
      }

      case 'get-tournament': {
        const payload = tournamentCodeSchema.parse(body);
        const lite = await TournamentService.getTournamentLite(payload.tournamentCode);
        return NextResponse.json({
          success: true,
          tournamentId: lite._id,
          tournamentCode: lite.tournamentId,
          status: lite.status,
          format: lite.format,
          isSandbox: lite.isSandbox,
          boards: lite.boards,
        });
      }

      case 'list-matches': {
        const payload = listMatchesSchema.parse(body);
        const { _id: tournamentObjectId } = await TournamentService.getTournamentIdOnly(payload.tournamentCode);
        const statuses = payload.statuses?.length ? payload.statuses : undefined;
        const query: Record<string, unknown> = {
          tournamentRef: tournamentObjectId,
        };
        if (statuses) {
          query.status = { $in: statuses };
        }

        if (payload.summaryOnly) {
          const grouped = await MatchModel.aggregate([
            { $match: query as any },
            { $group: { _id: '$status', count: { $sum: 1 } } },
          ]);
          const counts = grouped.reduce(
            (acc: { pending: number; ongoing: number; finished: number; total: number }, row: any) => {
              if (row?._id === 'pending') acc.pending = row.count;
              if (row?._id === 'ongoing') acc.ongoing = row.count;
              if (row?._id === 'finished') acc.finished = row.count;
              acc.total += row.count;
              return acc;
            },
            { pending: 0, ongoing: 0, finished: 0, total: 0 },
          );
          return NextResponse.json({ success: true, counts });
        }

        const limit = payload.limit || 300;
        const matches = await MatchModel.find(query as any)
          .select('_id status boardReference')
          .sort({ createdAt: 1 })
          .limit(limit)
          .lean();
        return NextResponse.json({
          success: true,
          matches: matches.map((match: any) => ({
            id: match._id?.toString?.() || String(match._id),
            status: match.status,
            boardReference: match.boardReference,
          })),
        });
      }

      default:
        return NextResponse.json({ error: `Unknown load-test action: ${actionName || 'missing'}` }, { status: 404 });
    }
  } catch (error) {
    const handled = handleError(error);
    return NextResponse.json(handled.body, { status: handled.status });
  }
}

export const POST = withApiTelemetry('/api/load-test/[action]', postHandler as any);
